In [1]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0], [1], [1], [0]])

np.random.seed(1)
W1 = np.random.rand(2, 2)
W2 = np.random.rand(2, 1)
b1 = np.zeros((1, 2))
b2 = np.zeros((1, 1))

lr = 0.1
epochs = 10000


for epoch in range(epochs):

    h = sigmoid(np.dot(X, W1) + b1)
    output = sigmoid(np.dot(h, W2) + b2)

    error = y - output
    d_output = error * sigmoid_derivative(output)

    error_hidden = d_output.dot(W2.T)
    d_hidden = error_hidden * sigmoid_derivative(h)


    W2 += h.T.dot(d_output) * lr
    b2 += np.sum(d_output, axis=0, keepdims=True) * lr

    W1 += X.T.dot(d_hidden) * lr
    b1 += np.sum(d_hidden, axis=0, keepdims=True) * lr

print("Final Output:")
print(np.round(output, 3))

print("Predicted Output:")
print(np.round(output))

Final Output:
[[0.066]
 [0.938]
 [0.938]
 [0.067]]
Predicted Output:
[[0.]
 [1.]
 [1.]
 [0.]]


In [1]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

def checkError(predicted):
    expected = np.array([[0],[1],[1],[0]])
    return np.any(np.abs(expected - predicted) > 0.001)

# XOR dataset
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
expected_output = np.array([[0],[1],[1],[0]])

# Get number of neurons
inputLayerNeurons = int(input("Enter no of input layer: "))
hiddenLayerNeurons = int(input("Enter no of hidden layer: "))
outputLayerNeurons = int(input("Enter no of output layer: "))

# Input weights
hidden_weights = []
for i in range(inputLayerNeurons):
    row = []
    for j in range(hiddenLayerNeurons):
        row.append(float(input("Enter weight: ")))
    hidden_weights.append(row)

# Output weights
output_weights = []
for i in range(hiddenLayerNeurons):
    row = []
    for j in range(outputLayerNeurons):
        row.append(float(input("Enter weight: ")))
    output_weights.append(row)

# Biases
hidden_bias = []
for i in range(hiddenLayerNeurons):
    hidden_bias.append(float(input("Enter hidden bias: ")))

output_bias = []
for i in range(outputLayerNeurons):
    output_bias.append(float(input("Enter output bias: ")))

hidden_weights = np.array(hidden_weights)
output_weights = np.array(output_weights)
hidden_bias = np.array([hidden_bias])
output_bias = np.array([output_bias])

print("\nInitial hidden weights:")
print(hidden_weights)

print("Initial hidden biases:")
print(hidden_bias)

print("Initial output weights:")
print(output_weights)

print("Initial output biases:")
print(output_bias)

# Training
lr = 0.1
epoch = 0
predicted_output = np.zeros((4,1))

while checkError(predicted_output):

    epoch += 1

    # Forward propagation
    hidden_activation = np.dot(inputs, hidden_weights) + hidden_bias
    hidden_output = sigmoid(hidden_activation)

    output_activation = np.dot(hidden_output, output_weights) + output_bias
    predicted_output = sigmoid(output_activation)

    # Backpropagation
    error = expected_output - predicted_output

    d_output = error * sigmoid_derivative(predicted_output)

    error_hidden = d_output.dot(output_weights.T)
    d_hidden = error_hidden * sigmoid_derivative(hidden_output)

    # Update weights and biases
    output_weights += hidden_output.T.dot(d_output) * lr
    output_bias += np.sum(d_output, axis=0, keepdims=True) * lr

    hidden_weights += inputs.T.dot(d_hidden) * lr
    hidden_bias += np.sum(d_hidden, axis=0, keepdims=True) * lr

# Final results
print("\nFinal hidden weights:")
print(hidden_weights)

print("Final hidden bias:")
print(hidden_bias)

print("Final output weights:")
print(output_weights)

print("Final output bias:")
print(output_bias)

print("\nOutput from neural network:")
print(predicted_output)

print("\nNo of epochs:")
print(epoch)

Enter no of input layer:  2
Enter no of hidden layer:  2
Enter no of output layer:  1
Enter weight:  3
Enter weight:  6
Enter weight:  4
Enter weight:  5
Enter weight:  2
Enter weight:  4
Enter hidden bias:  1
Enter hidden bias:  -6
Enter output bias:  -3.93



Initial hidden weights:
[[3. 6.]
 [4. 5.]]
Initial hidden biases:
[[ 1. -6.]]
Initial output weights:
[[2.]
 [4.]]
Initial output biases:
[[-3.93]]

Final hidden weights:
[[ 6.12370882 10.03281141]
 [ 6.12342151 10.0272853 ]]
Final hidden bias:
[[-9.34571401 -4.50662615]]
Final output weights:
[[-15.62277004]
 [ 14.81103743]]
Final output bias:
[[-7.06705554]]

Output from neural network:
[[9.99999968e-04]
 [9.99163980e-01]
 [9.99164113e-01]
 [8.53679468e-04]]

No of epochs:
14905082
